### ISSUE TITLE
Goal Timeline loading time

### ISSUE THREAD

**Issue by bharathkumarchowdary** [Finuncle-Fintech/lekkalu-frontend#602]
**Describe the bug**
Loading time for a Goal timeline in Goal Detail or Goal Edit page is too high

**To Reproduce**
Create an account on site
Add a loan liability with tenure >25 years
Add a Goal to reduce liability percent to less than 25%
Load the created timeline on browser and observe how much time it takes

**Comment by Sandip-Z** [comment]
@bharathkumarchowdary it seems Apex Chart is slow in general while plotting data. There are couple of hacks to make it faster, i will be looking into it.
source: https://stackoverflow.com/a/71827838/10785609

**Comment by bharathkumarchowdary** [comment]
@Sandip-Z , how is the issue resolved?

**Comment by Sandip-Z** [comment]
@bharathkumarchowdary did this PR not resolve the issue? 
PR: https://github.com/Finuncle-Fintech/lekkalu-frontend/pull/618

**Comment by bharathkumarchowdary** [comment]
@Sandip-Z , agree!
next time, please link PRs to issues while you work on them such that you don't have to manually close the issues
