### ISSUE TITLE
Lending Table Sort Field

### ISSUE THREAD

**Issue by bharathkumarchowdary** [Finuncle-Fintech/lekkalu-frontend#631]
I need to sort lending page table with name. I might also need to sort according to any of the columns in that table

**Comment by bharathkumarchowdary** [comment]
when I reduce the width of window to the minimum possible and scroll to end, I see this option to use app. Does it redirect to install or open the lending tab of the app installed app?
![image](https://github.com/user-attachments/assets/f497e171-2bfe-45f2-b37e-8026af509fd6)

**Comment by Sandip-Z** [comment]
@bharathkumarchowdary currently clicking this will take an authenticated user to dashboard. We need to add lending page route in our /src/utils/mobile-routes file to deep link with mobile application.

**Comment by bharathkumarchowdary** [comment]
can this be done in this same PR? or another issue for mobile repo?

**Comment by Sandip-Z** [comment]
@bharathkumarchowdary i pushed it in PR #639.
